### ISSUE TITLE
Use serial communication between Jetson and roboRIO

### ISSUE THREAD

**Issue by JacksonCoder** [SouthEugeneRoboticsTeam/PowerUp-2018#39]
So I know we discussed this on Slack, and I think it might be worth a shot. We'll need to pass an optional argument to the vision code to let it know to use serial communication, and we also need to change the DriveToCube method to use this form of communication instead. If we can get that working, communication would be much more reliable.

**Comment by andrewda** [comment]
Communication is now very reliable, but yes I think its worth a shot at serial if it's pretty straight forward.

**Comment by SUPERCILEX** [comment]
I'd prefer to keep using network tables since that's the standard and it works. If we go custom, there won't be any support. Also, don't see the point in changing something that works and is the "correct" way of doing it.

**Comment by andrewda** [comment]
Serial isn't too custom. And I'd actually consider serial to be the "correct" way because it's been more reliable for many teams, plus it's dozens of milliseconds faster. May as well try it out if we have time without the robot, there are a bunch of CD posts on it.

**Comment by SUPERCILEX** [comment]
Oh, ok. How do you use it in Java? The speed doesn't matter since we wait 20ms anyway, but if we're not alone, then why not.

**Comment by JacksonCoder** [comment]
There's the `usb4java` library.

**Comment by SUPERCILEX** [comment]
NETWORK TABLES
