### ISSUE TITLE
Auto selection webpage

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/PowerUp-2018#48]
Dumbboard sucks, maybe host the auto selection options on a webserver off the roboRIO? Let's talk about this.

**Comment by JacksonCoder** [comment]
Can the roboRIO host a website?

**Comment by SUPERCILEX** [comment]
@JacksonCoder Yes, but we've had a very successful run with Shuffleboard and even transferring config to a new drive laptop, so we're gonna stick with it for now. (Removing the graphs fixed the memory issues.)
